### ISSUE TITLE
About the mechanism of PAST correcting batch effects

### ISSUE THREAD

**Issue by XiHuYan** [lizhen18THU/PAST#1]
Hi, thanks for sharing this interesting work.

I read the corresponding paper, and found that you proposed transfer learning (TL) strategy and 3D stacking strategy to perform multi-slice integration. But I have not got the point of how your strategies correcting batch effects. Specifically, the TL strategy doesn't correct batch effects between slices and 3D stacking strategy doesn't build connections between slices.  Could you kindly explain this?

**Comment by lizhen18THU** [comment]
Hi, thanks for your interest in our work. 

In our paper, we have proved that based on the two strategies, PAST performs well in multi-slice integration and automatic annotation on datasets from the same technology (batch effect tend to be not obvious in these datasets), highlighting that PAST, as a basic representation learning method, can be extensively used for various tasks like multi-slice integration and automatic annotation. How, they are not specifically designed for batch correction and thus can not guarantee excellent performance in datasets with severe batch effects. Batch correction and alignment of slices from different technologies is a larger and complex problem. Here we only use these two strategies to preliminarily demonstrate the feasibility of the PAST framework on this problem.
